# Generated by Django 4.2.7 on 2023-11-24 05:57

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_picture",
            field=models.ImageField(
                default="user/car.jpg", upload_to=account.models.upload_data
            ),
            preserve_default=False,
        ),
    ]
