# Generated by Django 4.2.7 on 2023-11-17 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rideshare.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_type", models.CharField(max_length=10)),
                ("account_number", models.CharField(max_length=125)),
                ("back_code", models.CharField(max_length=4)),
                ("currency", models.CharField(max_length=4)),
                ("recipient_code", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="card_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_no", models.CharField(max_length=125)),
                ("expiry_date", models.CharField(max_length=10)),
                ("cvv", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="rider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to=rideshare.models.upload_data
                    ),
                ),
                ("route_from", models.CharField(max_length=125)),
                ("route_to", models.CharField(max_length=125)),
                ("trip_duration", models.CharField(default="1hr 30min", max_length=10)),
                ("bus_stop", models.CharField(max_length=125)),
                (
                    "licence",
                    models.FileField(
                        blank=True, null=True, upload_to=rideshare.models.upload_data
                    ),
                ),
                ("price", models.IntegerField()),
                ("is_active", models.BooleanField(default=False)),
                (
                    "account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rideshare.account",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=rideshare.models.upload_vehicle_pic,
                    ),
                ),
                (
                    "car_type",
                    models.CharField(
                        choices=[
                            ("Car", "Car"),
                            ("Bus", "Bus"),
                            ("Tricycle", "Tricycle"),
                            ("Motocycle", "Motorcycle"),
                        ],
                        max_length=10,
                    ),
                ),
                ("car_brand", models.CharField(max_length=125)),
                ("plate_no", models.CharField(max_length=125)),
                ("seat_cap", models.IntegerField()),
                ("seat_available", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passenger_count", models.IntegerField(default=0)),
                (
                    "rider_order_status",
                    models.CharField(
                        choices=[
                            ("Accepted", "Accepted"),
                            ("On Transit", "On Transit"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "rider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rideshare.rider",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rider",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rideshare.vehicle",
            ),
        ),
        migrations.CreateModel(
            name="passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to=rideshare.models.upload_data
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rideshare.card_detail",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_time", models.DateTimeField(auto_now=True)),
                ("has_paid", models.BooleanField(default=False)),
                (
                    "passenger_order_status",
                    models.CharField(
                        choices=[
                            ("Accepted", "Accepted"),
                            ("On Transit", "On Transit"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "passenger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rideshare.passenger",
                    ),
                ),
                (
                    "rider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rideshare.rider",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rideshare.trip",
                    ),
                ),
            ],
        ),
    ]
