# Generated by Django 4.2.7 on 2023-11-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rideshare", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="car_brand",
            new_name="brand",
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="car_type",
            new_name="type",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="seat_available",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
