# Generated by Django 4.2.7 on 2023-11-17 04:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rideshare", "0002_rename_car_brand_vehicle_brand_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_time",
            new_name="order_datetime",
        ),
    ]
