# Generated by Django 4.2.7 on 2023-11-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rideshare", "0004_alter_order_passenger_alter_order_rider"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reference",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
