# Generated by Django 4.2.7 on 2023-11-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rideshare", "0006_remove_passenger_card_order_rider_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="rider_order_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Accepted", "Accepted"),
                    ("On Transit", "On Transit"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
