# Generated by Django 4.2.7 on 2023-11-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rideshare", "0007_alter_trip_rider_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="rider_order_status",
            field=models.CharField(
                blank=True,
                choices=[("Accepted", "Accepted"), ("Declined", "Declined")],
                max_length=10,
                null=True,
            ),
        ),
    ]
