# Generated by Django 4.2.7 on 2023-11-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rideshare", "0008_alter_order_rider_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_type", models.CharField(max_length=10)),
                ("account_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=125)),
                ("back_code", models.CharField(max_length=4)),
                ("currency", models.CharField(max_length=4)),
                ("recipient_code", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="rider",
            name="account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rider",
                to="rideshare.accountdetail",
            ),
        ),
        migrations.DeleteModel(
            name="account",
        ),
    ]
