# Generated by Django 4.2.7 on 2023-11-19 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rideshare", "0009_accountdetail_alter_rider_account_delete_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="passenger_count",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="seat_available",
        ),
        migrations.AlterField(
            model_name="rider",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rider",
                to="rideshare.vehicle",
            ),
        ),
    ]
