# Generated by Django 4.2.7 on 2023-11-24 05:57

from django.db import migrations, models
import rideshare.models


class Migration(migrations.Migration):
    dependencies = [
        ("rideshare", "0011_alter_rider_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passenger",
            name="picture",
        ),
        migrations.RemoveField(
            model_name="rider",
            name="picture",
        ),
        migrations.AlterField(
            model_name="rider",
            name="trip_duration",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=rideshare.models.upload_data
            ),
        ),
    ]
