# Generated by Django 4.2.7 on 2023-11-27 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rideshare", "0015_rename_back_code_accountdetail_bank_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="rider",
        ),
    ]
