# Generated by Django 4.2.7 on 2023-11-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rideshare", "0016_remove_order_rider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="started_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2022-09-20 10:27:21.240752"
            ),
            preserve_default=False,
        ),
    ]
