# Generated by Django 4.2.7 on 2023-11-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rideshare", "0017_alter_trip_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="amount_raised",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
