# Generated by Django 4.2.7 on 2023-11-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rideshare", "0018_alter_order_order_datetime_alter_trip_amount_raised"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderlandmark",
            name="rider_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
