# Generated by Django 4.2.7 on 2023-11-12 18:43

from django.db import migrations, models
import django.db.models.deletion
import rider.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_type", models.CharField(max_length=10)),
                ("account_number", models.CharField(max_length=125)),
                ("back_code", models.CharField(max_length=4)),
                ("currency", models.CharField(max_length=4)),
                ("recipient_code", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to=rider.models.upload_vehicle_pic
                    ),
                ),
                ("type", models.CharField(max_length=125)),
                ("brand", models.CharField(max_length=125)),
                ("plate_no", models.CharField(max_length=125, unique=True)),
                ("seat_cap", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="rider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_from", models.CharField(max_length=125)),
                ("route_to", models.CharField(max_length=125)),
                ("bus_stop", models.CharField(max_length=125)),
                (
                    "licence",
                    models.FileField(
                        blank=True, null=True, upload_to=rider.models.upload_license
                    ),
                ),
                ("price", models.CharField(max_length=20)),
                (
                    "account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rider.account",
                    ),
                ),
            ],
        ),
    ]
