from django.urls import path
from .views import (
    PayForRide,
    SearchForRide,
    GoOnline,
    GoOffline,
    # VerifyPay,
    ViewOngoingTrips,
    AcceptOrder,
    ListRiderOrder,
    ViewATrip,
    EditRoute,
    GetVehicleDetail,
    EditUserProfile,
    ViewCompletedTrips,
    UpdateTripStatus,
    CreateUpdateBankAccount,
    ListAddLandmark,
    DeclineOrder,
    ViewAOrder,
    UpdateOrderStatus,
    YesConfirmedStatus,
    CreateOrder,
    ListCusOrder,
    Webhook,
    DeleteLandmark,
    GetUserProfile,
    EditUserProfile,
    GetRiderDetail,
)


urlpatterns = [
    path("search_for_ride/", SearchForRide.as_view(), name="search-for-ride"),
    path("pay_for_ride/", PayForRide.as_view(), name="pay-for-ride"),
    path("create_update_bankacnt/", CreateUpdateBankAccount.as_view(), name=""),
    path("user_detail/", GetUserProfile.as_view(), name="rider-detail"),
    path("get_order/<int:id>/", ViewAOrder.as_view(), name="get-order"),
    path("create_order/", CreateOrder.as_view(), name="create-order"),
    path("list_orders/", ListCusOrder.as_view(), name="list-order"),
    path("update_order_status/", UpdateOrderStatus.as_view(), name="list-order"),
    path("yes_confirmed/", YesConfirmedStatus.as_view(), name="list-order"),
    path("rider/go_online/", GoOnline.as_view(), name="Go-online"),
    path("list_add_landmark/", ListAddLandmark.as_view(), name="landmark"),
    path("delete_landmark/<int:id>/", DeleteLandmark.as_view(), name="delete-landmark"),
    path("rider/go_offline/", GoOffline.as_view(), name="Go-offline"),
    path("list_rider_orders/", ListRiderOrder.as_view(), name="list-rider-order"),
    path("accept_order/", AcceptOrder.as_view(), name="accept-order"),
    path("view_a_trip/", ViewATrip.as_view(), name="view-trip"),
    path("decline_order/", DeclineOrder.as_view(), name="decline-order"),
    path("edit_user_profile/", EditUserProfile.as_view(), name="edit-user"),
    path("vehicle_detail/", GetVehicleDetail.as_view(), name="vehicle-detail"),
    path("edit_route/", EditRoute.as_view(), name="edit-route"),
    path("update_trip_status/", UpdateTripStatus.as_view(), name="update-trip-status"),
    path("webhook/", Webhook.as_view(), name="webhook-url"),
    path("completed_trips/", ViewCompletedTrips.as_view(), name="completed-trips"),
    path("ongoing_trip/", ViewOngoingTrips.as_view(), name="ongoing-trips"),
    path("get_rider_detail/<int:id>/", GetRiderDetail().as_view(), name = "get-rider-detail")
]
